// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"time"
)

const TableNameBackendposdataPayment = "backendposdata_payment"

// BackendposdataPayment mapped from table <backendposdata_payment>
type BackendposdataPayment struct {
	Paymentid     string    `gorm:"column:paymentid" json:"paymentid"`
	Saleorderid   string    `gorm:"column:saleorderid" json:"saleorderid"`
	Seq           int32     `gorm:"column:seq;not null" json:"seq"`
	Paymentmethod int16     `gorm:"column:paymentmethod;not null" json:"paymentmethod"`
	Amount        float64   `gorm:"column:amount" json:"amount"`
	Amountrecieve float64   `gorm:"column:amountrecieve" json:"amountrecieve"`
	Possessionid  string    `gorm:"column:possessionid" json:"possessionid"`
	Posclientid   string    `gorm:"column:posclientid" json:"posclientid"`
	Createby      string    `gorm:"column:createby" json:"createby"`
	Createdate    time.Time `gorm:"column:createdate;not null" json:"createdate"`
	Isactive      int16     `gorm:"column:isactive;not null" json:"isactive"`
	Voidtype      int16     `gorm:"column:voidtype" json:"voidtype"`
	Voidby        string    `gorm:"column:voidby" json:"voidby"`
	Voiddate      time.Time `gorm:"column:voiddate" json:"voiddate"`
}

// TableName BackendposdataPayment's table name
func (*BackendposdataPayment) TableName() string {
	return TableNameBackendposdataPayment
}
