// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"time"
)

const TableNameBackendposdataSkuBranchPrice = "backendposdata_sku_branch_price"

// BackendposdataSkuBranchPrice mapped from table <backendposdata_sku_branch_price>
type BackendposdataSkuBranchPrice struct {
	Skuid      string    `gorm:"column:skuid;primaryKey" json:"skuid"`
	Merchantid string    `gorm:"column:merchantid;primaryKey" json:"merchantid"`
	Branchid   string    `gorm:"column:branchid;primaryKey" json:"branchid"`
	Price      float64   `gorm:"column:price" json:"price"`
	Startdate  time.Time `gorm:"column:startdate;not null;default:now()" json:"startdate"`
	Enddate    time.Time `gorm:"column:enddate" json:"enddate"`
	Isactive   int16     `gorm:"column:isactive;not null" json:"isactive"`
}

// TableName BackendposdataSkuBranchPrice's table name
func (*BackendposdataSkuBranchPrice) TableName() string {
	return TableNameBackendposdataSkuBranchPrice
}
