// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameGeography = "geographies"

// Geography mapped from table <geographies>
type Geography struct {
	Geographyid   int32  `gorm:"column:geographyid;primaryKey;autoIncrement:true" json:"geographyid"`
	Geographyname string `gorm:"column:geographyname;not null" json:"geographyname"`
}

// TableName Geography's table name
func (*Geography) TableName() string {
	return TableNameGeography
}
