// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNamePaymentMethod = "payment_method"

// PaymentMethod mapped from table <payment_method>
type PaymentMethod struct {
	Paymentmethodid int32  `gorm:"column:paymentmethodid;not null" json:"paymentmethodid"`
	Paymentname     string `gorm:"column:paymentname" json:"paymentname"`
}

// TableName PaymentMethod's table name
func (*PaymentMethod) TableName() string {
	return TableNamePaymentMethod
}
