// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameProdgroupProdcat = "prodgroup_prodcat"

// ProdgroupProdcat mapped from table <prodgroup_prodcat>
type ProdgroupProdcat struct {
	Prodgroupid int32 `gorm:"column:prodgroupid;not null" json:"prodgroupid"`
	Prodcatid   int32 `gorm:"column:prodcatid;not null" json:"prodcatid"`
}

// TableName ProdgroupProdcat's table name
func (*ProdgroupProdcat) TableName() string {
	return TableNameProdgroupProdcat
}
