// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameProdgroup = "prodgroup"

// Prodgroup mapped from table <prodgroup>
type Prodgroup struct {
	Prodgroupid int32  `gorm:"column:prodgroupid;primaryKey" json:"prodgroupid"`
	ThName      string `gorm:"column:th_name" json:"th_name"`
	EnName      string `gorm:"column:en_name" json:"en_name"`
}

// TableName Prodgroup's table name
func (*Prodgroup) TableName() string {
	return TableNameProdgroup
}
