// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameProvince = "provinces"

// Province mapped from table <provinces>
type Province struct {
	Provinceid     int32  `gorm:"column:provinceid;primaryKey;autoIncrement:true" json:"provinceid"`
	Provincecode   string `gorm:"column:provincecode;not null" json:"provincecode"`
	Provincename   string `gorm:"column:provincename;not null" json:"provincename"`
	Provincenameen string `gorm:"column:provincenameen;not null" json:"provincenameen"`
	Geographyid    int32  `gorm:"column:geographyid;not null" json:"geographyid"`
}

// TableName Province's table name
func (*Province) TableName() string {
	return TableNameProvince
}
