// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameReadallprovinceresp = "readallprovinceresp"

// Readallprovinceresp mapped from table <readallprovinceresp>
type Readallprovinceresp struct {
	Provinceid   int32  `gorm:"column:provinceid" json:"provinceid"`
	Provincename string `gorm:"column:provincename" json:"provincename"`
}

// TableName Readallprovinceresp's table name
func (*Readallprovinceresp) TableName() string {
	return TableNameReadallprovinceresp
}
