// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"time"
)

const TableNameSaleitem = "saleitem"

// Saleitem mapped from table <saleitem>
type Saleitem struct {
	Saleitemid    string    `gorm:"column:saleitemid" json:"saleitemid"`
	Saleorderid   string    `gorm:"column:saleorderid" json:"saleorderid"`
	Seq           int32     `gorm:"column:seq;not null" json:"seq"`
	Skuid         string    `gorm:"column:skuid" json:"skuid"`
	Productname   string    `gorm:"column:productname" json:"productname"`
	Price         float64   `gorm:"column:price" json:"price"`
	Quantity      float64   `gorm:"column:quantity" json:"quantity"`
	Fullprice     float64   `gorm:"column:fullprice" json:"fullprice"`
	Beforevatsale float64   `gorm:"column:beforevatsale" json:"beforevatsale"`
	Aftervatsale  float64   `gorm:"column:aftervatsale" json:"aftervatsale"`
	Posclientid   string    `gorm:"column:posclientid" json:"posclientid"`
	Branchid      string    `gorm:"column:branchid" json:"branchid"`
	Compcode      string    `gorm:"column:compcode" json:"compcode"`
	Promotionid   int32     `gorm:"column:promotionid" json:"promotionid"`
	Createby      string    `gorm:"column:createby" json:"createby"`
	Createdate    time.Time `gorm:"column:createdate;not null" json:"createdate"`
	Isactive      int16     `gorm:"column:isactive;not null" json:"isactive"`
	Voidtype      int16     `gorm:"column:voidtype" json:"voidtype"`
	Voidby        string    `gorm:"column:voidby" json:"voidby"`
	Voiddate      time.Time `gorm:"column:voiddate" json:"voiddate"`
}

// TableName Saleitem's table name
func (*Saleitem) TableName() string {
	return TableNameSaleitem
}
