// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"time"
)

const TableNameUseraccount = "useraccount"

// Useraccount mapped from table <useraccount>
type Useraccount struct {
	Userid      string    `gorm:"column:userid" json:"userid"`
	Login       string    `gorm:"column:login" json:"login"`
	Password    string    `gorm:"column:password" json:"password"`
	Lastlogin   time.Time `gorm:"column:lastlogin" json:"lastlogin"`
	Authtype    string    `gorm:"column:authtype" json:"authtype"`
	Usertype    string    `gorm:"column:usertype" json:"usertype"`
	Failedcount int32     `gorm:"column:failedcount" json:"failedcount"`
	Createby    string    `gorm:"column:createby" json:"createby"`
	Createdate  time.Time `gorm:"column:createdate;not null" json:"createdate"`
	Updateby    string    `gorm:"column:updateby" json:"updateby"`
	Updatedate  time.Time `gorm:"column:updatedate;not null" json:"updatedate"`
	Isactive    bool      `gorm:"column:isactive;not null" json:"isactive"`
}

// TableName Useraccount's table name
func (*Useraccount) TableName() string {
	return TableNameUseraccount
}
