// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"time"
)

const TableNameBackendposdatasku = "backendposdatasku"

// Backendposdatasku mapped from table <backendposdatasku>
type Backendposdatasku struct {
	Skuid           string    `gorm:"column:skuid;primaryKey" json:"skuid"`
	Barcodepos      string    `gorm:"column:barcodepos" json:"barcodepos"`
	Productname     string    `gorm:"column:productname" json:"productname"`
	Brandid         int32     `gorm:"column:brandid" json:"brandid"`
	Productgroupid  int32     `gorm:"column:productgroupid" json:"productgroupid"`
	Productcatid    int32     `gorm:"column:productcatid" json:"productcatid"`
	Productsubcatid int32     `gorm:"column:productsubcatid" json:"productsubcatid"`
	Productsizeid   int32     `gorm:"column:productsizeid" json:"productsizeid"`
	Productunit     int32     `gorm:"column:productunit" json:"productunit"`
	Packsize        string    `gorm:"column:packsize" json:"packsize"`
	Unit            int32     `gorm:"column:unit" json:"unit"`
	Banforpracharat int32     `gorm:"column:banforpracharat" json:"banforpracharat"`
	Isvat           int16     `gorm:"column:isvat" json:"isvat"`
	Createby        string    `gorm:"column:createby" json:"createby"`
	Createdate      time.Time `gorm:"column:createdate;not null;default:now()" json:"createdate"`
	Isactive        int16     `gorm:"column:isactive;not null" json:"isactive"`
	Merchantid      string    `gorm:"column:merchantid" json:"merchantid"`
	Mapsku          string    `gorm:"column:mapsku" json:"mapsku"`
	Isfixprice      int16     `gorm:"column:isfixprice;not null" json:"isfixprice"`
}

// TableName Backendposdatasku's table name
func (*Backendposdatasku) TableName() string {
	return TableNameBackendposdatasku
}
