// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameBrand = "brand"

// Brand mapped from table <brand>
type Brand struct {
	Brandid int32  `gorm:"column:brandid;not null" json:"brandid"`
	ThBrand string `gorm:"column:th_brand" json:"th_brand"`
	EnBrand string `gorm:"column:en_brand" json:"en_brand"`
}

// TableName Brand's table name
func (*Brand) TableName() string {
	return TableNameBrand
}
