// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameCategory = "categories"

// Category mapped from table <categories>
type Category struct {
	Prodcatid int32  `gorm:"column:prodcatid;not null" json:"prodcatid"`
	ThName    string `gorm:"column:th_name" json:"th_name"`
	EnName    string `gorm:"column:en_name" json:"en_name"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
