// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameDistrict = "districts"

// District mapped from table <districts>
type District struct {
	Districtid     int32  `gorm:"column:districtid;primaryKey;autoIncrement:true" json:"districtid"`
	Districtcode   string `gorm:"column:districtcode;not null" json:"districtcode"`
	Districtname   string `gorm:"column:districtname;not null" json:"districtname"`
	Districtnameen string `gorm:"column:districtnameen;not null" json:"districtnameen"`
	Provinceid     int32  `gorm:"column:provinceid;not null" json:"provinceid"`
}

// TableName District's table name
func (*District) TableName() string {
	return TableNameDistrict
}
