// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameMerchant = "merchant"

// Merchant mapped from table <merchant>
type Merchant struct {
	Merchantid      string `gorm:"column:merchantid;default:uuid_generate_v4()" json:"merchantid"`
	Merchantname    string `gorm:"column:merchantname" json:"merchantname"`
	Merchantaddress string `gorm:"column:merchantaddress" json:"merchantaddress"`
	Merchanttel     string `gorm:"column:merchanttel" json:"merchanttel"`
	Taxid           string `gorm:"column:taxid" json:"taxid"`
	Isactive        bool   `gorm:"column:isactive" json:"isactive"`
	Isvat           bool   `gorm:"column:isvat" json:"isvat"`
}

// TableName Merchant's table name
func (*Merchant) TableName() string {
	return TableNameMerchant
}
