// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNamePosclient = "posclient"

// Posclient mapped from table <posclient>
type Posclient struct {
	Posclientid       string `gorm:"column:posclientid;default:uuid_generate_v4()" json:"posclientid"`
	Branchid          string `gorm:"column:branchid" json:"branchid"`
	Merchantid        string `gorm:"column:merchantid" json:"merchantid"`
	Rdnumber          string `gorm:"column:rdnumber" json:"rdnumber"`
	Isdrawer          bool   `gorm:"column:isdrawer" json:"isdrawer"`
	Isbarcode         bool   `gorm:"column:isbarcode" json:"isbarcode"`
	Iscash            bool   `gorm:"column:iscash" json:"iscash"`
	Isqrcode          bool   `gorm:"column:isqrcode" json:"isqrcode"`
	Ispaotang         bool   `gorm:"column:ispaotang" json:"ispaotang"`
	Istongfah         bool   `gorm:"column:istongfah" json:"istongfah"`
	Iscoupon          bool   `gorm:"column:iscoupon" json:"iscoupon"`
	Sessiontype       int16  `gorm:"column:sessiontype" json:"sessiontype"`
	Barcodereadertype int16  `gorm:"column:barcodereadertype" json:"barcodereadertype"`
	Printertype       int16  `gorm:"column:printertype" json:"printertype"`
	Isactive          bool   `gorm:"column:isactive;not null" json:"isactive"`
	Posrunning        string `gorm:"column:posrunning" json:"posrunning"`
	Frposrunning      string `gorm:"column:frposrunning" json:"frposrunning"`
	Paymentmode       int16  `gorm:"column:paymentmode" json:"paymentmode"`
}

// TableName Posclient's table name
func (*Posclient) TableName() string {
	return TableNamePosclient
}
