// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameProdsubcat = "prodsubcat"

// Prodsubcat mapped from table <prodsubcat>
type Prodsubcat struct {
	Prodsubcatid int32  `gorm:"column:prodsubcatid;not null" json:"prodsubcatid"`
	ThName       string `gorm:"column:th_name" json:"th_name"`
	EnName       string `gorm:"column:en_name" json:"en_name"`
}

// TableName Prodsubcat's table name
func (*Prodsubcat) TableName() string {
	return TableNameProdsubcat
}
