// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNamePromotionAppliedItemsID = "promotion_applied_items_id"

// PromotionAppliedItemsID mapped from table <promotion_applied_items_id>
type PromotionAppliedItemsID struct {
	Promotiondetailid string `gorm:"column:promotiondetailid" json:"promotiondetailid"`
	Promotionid       string `gorm:"column:promotionid" json:"promotionid"`
	Skuid             string `gorm:"column:skuid" json:"skuid"`
}

// TableName PromotionAppliedItemsID's table name
func (*PromotionAppliedItemsID) TableName() string {
	return TableNamePromotionAppliedItemsID
}
