// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"time"
)

const TableNamePromotion = "promotion"

// Promotion mapped from table <promotion>
type Promotion struct {
	Promotionid   string    `gorm:"column:promotionid" json:"promotionid"`
	Promotionyype int32     `gorm:"column:promotionyype;not null" json:"promotionyype"`
	Startdate     time.Time `gorm:"column:startdate;not null" json:"startdate"`
	Enddate       time.Time `gorm:"column:enddate;not null" json:"enddate"`
	Description   string    `gorm:"column:description" json:"description"`
	Conditions    string    `gorm:"column:conditions;not null" json:"conditions"`
}

// TableName Promotion's table name
func (*Promotion) TableName() string {
	return TableNamePromotion
}
