// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"time"
)

const TableNameUserlogin = "userlogin"

// Userlogin mapped from table <userlogin>
type Userlogin struct {
	Userid      string    `gorm:"column:userid" json:"userid"`
	Posclientid string    `gorm:"column:posclientid" json:"posclientid"`
	Lastlogin   time.Time `gorm:"column:lastlogin" json:"lastlogin"`
	Lastlogout  time.Time `gorm:"column:lastlogout" json:"lastlogout"`
	Version     string    `gorm:"column:version" json:"version"`
}

// TableName Userlogin's table name
func (*Userlogin) TableName() string {
	return TableNameUserlogin
}
