DROP TABLE IF EXISTS backendposdata_sku_branch_price;
DROP TABLE IF EXISTS backendposdatasku;
DROP TABLE IF EXISTS brand;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS prodcat;
DROP TABLE IF EXISTS prodcat_prodsubcat;
DROP TABLE IF EXISTS prodgroup;
DROP TABLE IF EXISTS prodgroup_prodcat;
DROP TABLE IF EXISTS prodsubcat;
DROP TABLE IF EXISTS promotion;
DROP TABLE IF EXISTS promotion_applied_items_id;
-- DROP TABLE IF EXISTS geographies;
-- DROP TABLE IF EXISTS provinces;
-- DROP TABLE IF EXISTS districts;
-- DROP TABLE IF EXISTS subdistricts;
-- DROP TABLE IF EXISTS branch;
-- DROP TABLE IF EXISTS merchant;
-- DROP TABLE IF EXISTS posclient;
-- DROP TABLE IF EXISTS useraccount;
-- DROP TABLE IF EXISTS userlogin;
