// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	
	"encoding/json"
	"time"
)

type Branch struct {
	BranchID          *string `json:"branch_id"`
	MerchantID        *string `json:"merchant_id"`
	BranchNo          *string `json:"branch_no"`
	BranchName        *string `json:"branch_name"`
	BranchAddress     *string `json:"branch_address"`
	BranchEmail       *string `json:"branch_email"`
	AccountName       *string `json:"account_name"`
	AccountCode       *string `json:"account_code"`
	IsActive          interface{}    `json:"is_active"`
	BranchAddress2    *string `json:"branch_address2"`
	BranchSubdistrict *string `json:"branch_subdistrict"`
	BranchDistrict    *string `json:"branch_district"`
	BranchProvince    *string `json:"branch_province"`
	BranchZipcode     *string `json:"branch_zipcode"`
	IsInventory       interface{}    `json:"is_inventory"`
	IsAlertInventory  interface{}    `json:"is_alert_inventory"`
}

type PaymentMethod struct {
	Paymentmethodid int32          `json:"paymentmethodid"`
	Paymentname     *string `json:"paymentname"`
}

type Posclient struct {
	PosClientID       *string `json:"pos_client_id"`
	BranchID          *string `json:"branch_id"`
	MerchantID        *string `json:"merchant_id"`
	RdNumber          *string `json:"rd_number"`
	IsDrawer          *int16  `json:"is_drawer"`
	IsBarcode         *int16  `json:"is_barcode"`
	IsCash            *int16  `json:"is_cash"`
	IsQrcode          *int16  `json:"is_qrcode"`
	IsPaotang         *int16  `json:"is_paotang"`
	IsTongfah         *int16  `json:"is_tongfah"`
	IsCoupon          *int16  `json:"is_coupon"`
	SessionType       *int16  `json:"session_type"`
	BarcodeReaderType *int16  `json:"barcode_reader_type"`
	PrinterType       *int16  `json:"printer_type"`
	IsActive          int16          `json:"is_active"`
	PosRunning        *string `json:"pos_running"`
	FrPosRunning      *string `json:"fr_pos_running"`
	PaymentMode       *int16  `json:"payment_mode"`
}

type Prodgroup struct {
	Prodgroupid int32          `json:"prodgroupid"`
	ThName      *string `json:"th_name"`
	EnName      *string `json:"en_name"`
}

type Promotion struct {
	Promotionid    *string  `json:"promotionid"`
	Promotiontitle *string  `json:"promotiontitle"`
	Promotiontype  int32           `json:"promotiontype"`
	Startdate      time.Time       `json:"startdate"`
	Enddate        time.Time       `json:"enddate"`
	Description    *string  `json:"description"`
	Condition      json.RawMessage `json:"condition"`
}

type PromotionAppliedItemsID struct {
	PromotiondetailID *string `json:"promotiondetail_id"`
	Promotionid       *string `json:"promotionid"`
	Skuid             *string `json:"skuid"`
}
