// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetPaymentMethod(ctx context.Context) ([]PaymentMethod, error)
	GetProdgroup(ctx context.Context) ([]Prodgroup, error)
	GetPromotion(ctx context.Context) ([]Promotion, error)
	GetPromotionAppliedItemID(ctx context.Context) ([]PromotionAppliedItemsID, error)
	GetPromotionByID(ctx context.Context, promotionid sql.NullString) (Promotion, error)
}

var _ Querier = (*Queries)(nil)
