// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
	
)

type Querier interface {
	GetPaymentConfig(ctx context.Context) ([]GetPaymentConfigRow, error)
	GetPaymentMethod(ctx context.Context) ([]PaymentMethod, error)
	GetPosClientMethod(ctx context.Context, posClientID *string) ([]GetPosClientMethodRow, error)
	GetProdgroup(ctx context.Context) ([]Prodgroup, error)
	GetProdgroupByID(ctx context.Context, prodgroupid int32) ([]Prodgroup, error)
	GetPromotion(ctx context.Context) ([]Promotion, error)
	GetPromotionAppliedItemID(ctx context.Context) ([]PromotionAppliedItemsID, error)
	GetPromotionByID(ctx context.Context, promotionid *string) (Promotion, error)
	PostPromotion(ctx context.Context, arg PostPromotionParams) error
	PostPromotionApplied(ctx context.Context, arg PostPromotionAppliedParams) error
	PostPromotionTable(ctx context.Context, arg PostPromotionTableParams) error
}

var _ Querier = (*Queries)(nil)
